#+TITLE:Syllabus (FIN 302) Financial Management Principles
#+AUTHOR: Matthew Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
# #+options: toc:nil


#+BEGIN_CENTER
SUNY POLYTECHNIC INSTITUTE

SCHOOL OF BUSINESS ADMINISTRATION
#+END_CENTER

**Instructor**: Matthew Brigida, Ph.D.

**Office**: Online Summer 2022 | On Campus Office is Donovan 1277

**Office Hours**: On-request I will create a BB Collaborate session where you can log in and ask questions.
# Monday and Wednesday 12--2pm, and 

**Email**:  matthew.brigida@sunypoly.edu

**Class Location**: Online (Asynchronous)

**Class Day/Time**: Asynchronous Online
#+begin_comment
##Wednesday 6:00pm to 9:30pm.  We will meet via Blackboard Collaborate. All lectures will also be recorded.
#+end_comment

**Text**: [[https://www.amazon.com/dp/0073382469/ref=olp_product_details?_encoding=UTF8&me=][Essentials of Corporate Finance, 7th ed, ISBN: 978-0073382463]] | [[https://www.amazon.com/gp/offer-listing/0073382469/ref=dp_olp_used?ie=UTF8&condition=used][Used Copies usually starting from about $4]] You also may use other editions of the text.

**Lecture Videos**: [[https://www.youtube.com/playlist?list=PLRK1VeglPb4MpA0hq3lhLn8olIz3NLai1][Introduction to Corporate Finance]]

**Lecture Notes**: [[https://financial-education.github.io/intro_corp_fin.html][Financial Education]]

* Description

**Course Catalog Description**: General principles of corporate/managerial finance are presented. Topics include the tax environment, an overview of financial planning and control, working capital management, long term financing, time value of money, capital budgeting, cost of capital, dividend policy, agency theory, and international financial issues. Responsibilities and functions performed by financial analysts, financial managers, and chief financial managers are discussed. (Pre-requisite: ACC 201 or equivalent.)

** Overview

-  This course will present the fundamentals of managerial finance as a vital part of the complete business ecosystem. Importance is placed on becoming familiar with the rudimentary tools and techniques that act as the basis for all further study and function of finance.

-  Emphasis is also placed on exploring the human, technological, and environmental impacts on financial decision making and the societal variables that facilitate positive (financial and social) outcomes.

-  Attention to current events and linkage between financial markets and corporate decision-making and vis-a-vis is discussed.

-  Introduction to the role of the change agent and changing technology in financial analysis and financial decision-making processes.

** Course Learning Outcomes & Objectives

CLO 1. Technical Competence: Adept in applying technology to solve institutional problems and enable effective financial decision making.

CLO 2. Analytical Problem Framing: Demonstrate individual capacity to evaluate and deploy analytical methods selected from a diverse portfolio of tools analyze and manage common financial decisions.

CLO 3. Strategic and Integrative Thinking: Understand the baseline resources available for analyzing and managing a firm’s financial performance. Including collecting data, processing information and evaluating and communicating outcomes with partners; differentiate between the accounting function as a preparer of data and information and the finance function as a user of information for decision making and the role of ethics in the process.

CLO 4. Leadership and Communication: Be capable of expressing key financial concepts and terms commonly used in the field; by using effective written, oral and interpersonal communications to contribute to the financial performance of domestic firms, global organizations and other international relationships.

* Exams

#+begin_comment
There will be three exams (two during the semester and a final exam).  All exams will be multiple choice.

Failure to take an exam will result in a grade of 0, unless it is due to a **verifiable** medical or family emergency.  In such a case you must provide documentation.
#+end_comment

There will be two exams.  The exams will be multiple choice. Failure to complete an exam by the due date will result in a grade of 0.

* Assignments

#+begin_comment
Value a tolling agreement on a natural gas fired power plant near Boston Mass via discounted cash flows.  This project will make heavy use of core concepts learned in this course---namely the calculation of cash flows and the time-value-of-money.  [[https://www.eia.gov/electricity/wholesale/#history][Data are here]].
#+end_comment

There are 4 assignments under Content > Assignments in BlackBoard.

#+begin_comment
<!-- add project with banking research data set here -->
#+end_comment


#+begin_comment
In groups, students will either:

1.  Value a tolling agreement on a natural gas fired power plant near Boston Mass via discounted cash flows.  This project will make heavy use of core concepts learned in this course---namely the calculation of cash flows and the time-value-of-money.  [[https://www.eia.gov/electricity/wholesale/#history][Data are here]].

or 

2. Estimate the relationship between capital levels and measures of bank income and performance.

In addition, students will gain experience handling data, and making reasonable assumptions necessary in real-world analyses.
#+end_comment

* Attendance/Quizzes/Participation

#+begin_comment
Throughout the semester I will take attendance, give unanounced quizzes, and otherwise evaluate your participation.  Failure to attend class and participate will reduce your participation score, unless your absence is due to a **verifiable** medical or family emergency.  In such a case you must provide documentation.
#+end_comment

There is no attendance/participation grade.

* Grading

#+BEGIN_CENTER

| Item         | Points |
|--------------+--------|
| Exam 1       |     40 |
| Exam 2       |     40 |
# | Final Exam   |     30 |
| Assignments  |     20 |
|--------------+--------|
| Total Points |    100 |
|--------------+--------|

# | Final Exam                                 |     25 |
# | Project                                    |     15 |
# | Attendance/Quizzes/Participation           |     20 | 

#+END_CENTER

#+BEGIN_CENTER
**Final grades will be assigned according to the following scale**:
#+END_CENTER

- 90 - 100 A
- 80 - 89.9 B
- 70 - 79.9 C
- 60 - 69.9 D
- $<$ 60 F

#+BEGIN_QUOTE
+/- grades may be assigned at the instructors discretion.
#+END_QUOTE

** An Important Note on Grading

#+BEGIN_QUOTE
There is no special consideration if you need a certain grade in this course to graduate.  **If you require a certain grade in this class to graduate it is your responsibility to earn that grade.** Specifically if you receive a `D` in this course I will not allow you to do extra assignments after the course is complete in exchange for a higher grade. 
#+END_QUOTE

* Tentative Outline by Week
  
We will cover chapters 1 through 14.  Since this course is asynchronous, you
have a measure of flexibility regarding when you cover each chapter.  The due
dates for the exams/assignments are listed below.

**You will receive a 0 if you do not hand in an exam or assignment by the due date.  Because you have a month to complete the exams/assignments, I will not accept late submissions for any reason.**

** Exam Due Dates

- June 24: Exam 1 Due
- July 24: Exam 2 Due

** Assignment Due Dates

- June 24: DEF14A and Debt to Equity Ratio
- July 24: Stock Market and CAPM

# ** Exam Due Dates
# 
# - October 1: Exam 1 Due
# - November 19: Exam 2 Due
# - December 13: Final Exam Due
# 
# ** Assignment Due Dates
# 
# - October 1: DEF14A and Debt to Equity Ratio
# - November 19: Stock Market and CAPM
  

#+begin_comment
- 1/21: Chapter 1 & 2
- 1/28:  Chapter 3 and 4
- 2/4: Chapter  5
- 2/11: Chapter 6
- 2/18: @@html:<span style="color:red">**Exam 1**</span>@@
- 2/25: Chapter 7
- 3/3: Chapter 8
- 3/10: Chapter 9
- 3/17: Spring Break
- 3/24: Chapter 10
- 4/1:  Chapter 11 & Chapter 12
- 4/7: @@html:<span style="color:red">**Exam 2**</span>@@
- 4/15: Chapter 13 and 14
- 4/22: Chapter 15
- 4/29: exam review
#+end_comment

#+begin_comment
- 8/26: Chapter 1 & 2 
- 9/2:  Chapter 3 and 4 
- 9/9: Chapter  5 
- 9/16: Chapter 6 
- 9/23: @@html:<span style="color:red">**Exam 1**</span>@@
- 9/30: Chapter 7 
- 10/7: Chapter 8 
- 10/14: Chapter 9 
- 10/21: Chapter 10 and 11 
- 10/28: Chapter 12 
- 11/4: @@html:<span style="color:red">**Exam 2**</span>@@
- 11/11: Chapter 13 and 14 
- 11/18: Chapter 15 
- 11/25: exam review 
- 12/2: exam review
#+end_comment
  

#+begin_comment

# * Lecture Notes by Topic

[[https://financial-education.github.io/intro_corp_fin.html][List of Lecture Notes]]

# * Lecture Videos by Chapter

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/kkGcNM2yOaU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></frame>
#+END_EXPORT

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/WDXreexyIoQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/HJxm-jzi2bM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/MI4BCgS883c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+END_EXPORT

#+end_comment

* How To Ask Questions

How to properly phrase a question is important in the workplace as well as in courses, such as ours, where much of the interaction is online.  Remember when formulating your question, *you get what you give*.  If you simply say, "I don't understand", then I have very little information to work with and so I can't help.  I'll just say to rewatch the relevant video.

Alternatively, if you say, "I calculated a stock's expected return using the CAPM and it is negative.  Can this be correct?".  Here you have (1) let me know what you have done, (2) your result, and (3) what you don't understand. In this case I can ask (1) which stock, and (2) is your beta negative, and proceed to explain whether your calculation is correct.

[[https://stackoverflow.com/help/how-to-ask][See this post.]]  

* Email Communication

Questions about course material should be posted to the most relevant discussion board.  Email should only be used for personal matters.  When sending an email, be sure to put the course in the subject line (FIN 302). 



#+begin_comment
# * Communication by Email

# ** When It Is Appropriate

# This is an in-class course, and you are responsible for knowing what has taken place in class.  In the case of an unexcused absence, you should come by office hours or talk with classmates to learn what you missed. It is not appropriate to email me.

# In the case of an absence due to medical or family emergency, you can email me your documentation along with questions regarding what you missed.  However you can also stop by office hours if convenient.

# ** How to Write an Email

# ~Subject:~ FIN 302: [Clear Subject Here]

# ~Body:~

# Dear Professor (or Dr.) Brigida,

# [Text of email here.]

# Sincerely, 

# [Your name.]

# ** How Not to Write and Email

# ~Subject:~ Missed Class (I don't know what class you are in.)

# ~Body:~

# Matthew, (Wrong, we are not on a first name basis.)

# Can you tell me what I missed?  (No, you are responsible.)
#+end_comment


#+BEGIN_COMMENT

# * A note on learning in the course and in finance generally:

In this course I will teach you how to answer questions, and solve financial problems.  This is different than teaching you the answers to text questions, and the distinction here is important.  When you start to work you will be faced with unique financial situations and problems to solve.  You will have to figure out how to solve the problem.  To do so you will apply the concepts and skills you learn in this course to your particular situation.  You will never be faced with a textbook problem while working however.   

As a practical example, it makes much more sense for you to ask me "how do I solve this problem", rather than "what is the answer to this problem".  You might say, 'well I just want to check if my work is correct'.  If this is the case, then show me the work, so I can see both how you solved it and your numerical answer.
#+END_COMMENT

#+begin_comment
<!-- * Instructor's Notes -->

<!-- -  **Understanding vs Computation**: This course will focus on understanding financial concepts over merely calculating a number. Any calculation you will see as an undergrad has already been implemented in 20+ different programming languages.  You will never get a job as a calculator.  The value of the financial analyst is in undertanding what a calculation does, what the output means, etc.  You must be able to use the appropriate calculation in a given situation, and able to understand its output to make financial decisions. -->

<!-- -  **Spreadsheet Skills**:  The above does not mean you do not need to know how to calculate financial values.  You need to be able to do so in a spreadsheet, and increasingly with some programming language (python, javascript, R, etc). The point here is that the correct calculation is the minimal amount of work you can do.  It is the easiest part.  The harder, and more important aspect, is understanding what you are doing.  -->

<!-- -  Accordingly many *computation* questions on the exams can be solved through logic---knowing that 3 of 4 potential answers are not possible. -->
#+end_comment

* Guidelines and Accommodations

Academic Integrity Policy Students Enrolled in this course are required to understand and fully comply with all aspects of the Academic Integrity Policy as described in the SUNY Polytechnic Institute Handbook (available at:  https://sunypoly.edu/pdf/student_handbook.pdf )

** Course Syllabus Disclosure Statement Fall 2021

#+begin_quote
Accommodations for Students with Disabilities

In compliance with the Americans with Disabilities Act of 1990 and Section 504 of the Rehabilitation Act, SUNY Polytechnic Institute is committed to ensuring comprehensive educational access and accommodations for all registered students seeking access to meet course requirements and fully participate in programs and activities.  Students with documented disabilities or medical conditions are encouraged to request these services by registering with the Office of Disability Services.  Please request accommodations early in the semester, or as soon as you become registered with Disability Services, so that we have adequate time to arrange your approved academic accommodation/s.  Once Disability Services creates your accommodation plan, it is your responsibility to provide me a copy of the accommodation plan.

For information related to these services or to schedule an appointment, please contact the Office of Disability Services using the information provided below. 

Leslie K. Reid, Director (she/her/hers)
Office of Disability Services 
reidl@sunypoly.edu 
(315) 792-7170 
Utica Campus 
Peter J. Cayan Library, L145 
Albany Campus 
Suite 309, Students Services Office 
NanoFab South 
#+end_quote


