---
title: 
date: "January 15, 2018"
output: 
  html_document:
    toc: true
    #toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
---

# Syllabus (FIN 302) Financial Management Principles
<br>
<br>
<center>
<b>SUNY POLYTECHNIC INSTITUTE</b>

<b>SCHOOL OF BUSINESS ADMINISTRATION</b>
</center>
<br>
<br>
**Instructor**: Matthew Brigida, Ph.D.

**Office**: 

**Email**:  

**Course Start Date**: 

**Course End Date**: 

**Class Location**:  Hybrid (in class and Online (Blackboard))

**Text**: [Essentials of Corporate Finance, 7th ed, ISBN: 978-0073382463](https://www.amazon.com/dp/0073382469/ref=olp_product_details?_encoding=UTF8&me=) [Used Copies usually starting from about $4](https://www.amazon.com/gp/offer-listing/0073382469/ref=dp_olp_used?ie=UTF8&condition=used).  You also may use other editions of the text.

**Supplementary Materials**: [5-Minute Finance](https://www.5minutefinance.org/).  There may be additional topics in the [Fundamentals and Corporate Finance Sections here.](https://github.com/FinancialMarkets/5MinuteFinance)

**Important Dates**

**Midterm Exam:**  

**Final Exam:**  

## Description

**Course Catalog Description**: General principles of corporate/managerial finance are presented. Topics include the tax environment, an overview of financial planning and control, working capital management, long term financing, time value of money, capital budgeting, cost of capital, dividend policy, agency theory, and international financial issues. Responsibilities and functions performed by financial analysts, financial managers, and chief financial managers are discussed. (Pre-requisite: ACC 201 or equivalent.)

### Overview:

-  This course will present the fundamentals of managerial finance as a vital part of the complete business ecosystem. Importance is placed on becoming familiar with the rudimentary tools and techniques that act as the basis for all further study and function of finance.

-  Emphasis is also placed on exploring the human, technological, and environmental impacts on financial decision making and the societal variables that facilitate positive (financial and social) outcomes.

-  Attention to current events and linkage between financial markets and corporate decision-making and vis-a-vis is discussed.

-  Introduction to the role of the change agent and changing technology in financial analysis and financial decision-making processes.

### Course Learning Outcomes & Objectives:

CLO 1. Technical Competence: Adept in applying technology to solve institutional problems and enable effective financial decision making.

CLO 2. Analytical Problem Framing: Demonstrate individual capacity to evaluate and deploy analytical methods selected from a diverse portfolio of tools analyze and manage common financial decisions.

CLO 3. Strategic and Integrative Thinking: Understand the baseline resources available for analyzing and managing a firm’s financial performance. Including collecting data, processing information and evaluating and communicating outcomes with partners; differentiate between the accounting function as a preparer of data and information and the finance function as a user of information for decision making and the role of ethics in the process.

CLO 4. Leadership and Communication: Be capable of expressing key financial concepts and terms commonly used in the field; by using effective written, oral and interpersonal communications to contribute to the financial performance of domestic firms, global organizations and other international relationships.

## Grading


## Guidelines and Accommodations

Academic Integrity Policy Students Enrolled in this course are required to understand and fully comply with all aspects of the Academic Integrity Policy as described in the SUNY Polytechnic Institute Handbook (available at:  https://sunypoly.edu/pdf/student_handbook.pdf )

### Accommodations for Students with Disabilities

Students with disabilities are welcome at SUNY Polytechnic Institute.
The Disabilities Services Office is located in the Career Services Suite, B101, Kunsela Hall
Hours: Monday through Friday 8:30 a.m. – 4:30 p.m. or by appointment.
E-mail: suzanne.sprague@sunyit.edu
Phone: (315) 792-7170

Any current or prospective student may contact our office to discuss potential academic accommodations. Typical accommodations include extended time for testing, testing in a quiet location, textbooks in alternate format, and others as determined by the nature of the disability. These accommodations must be supported by documentation from outside sources, such as a recent psychological evaluation or medical report that clearly identifies the nature of your disability and the impact of your disability or treatment upon learning. (SUNY Poly is not responsible for providing evaluation or funding to complete the needed documentation.)

The Disabilities Services Office will assist with requesting the required documentation or exploring resources that may provide testing or documentation. Once documentation is received, the Disability Counselor meets with the student to discuss the information based on his or her experiences and perspective. A student’s explanation of how his or her disability affects learning and what accommodations are needed is extremely important. Once a determination is made regarding the reasonable and appropriate accommodations, a plan is written which students sign and share with instructors. This plan does not disclose the nature of the disability, although many students have found that discussing their circumstances with faculty can be helpful.

Accommodations are implemented to ensure compliance with the Americans with Disabilities Act of 1990 (ADA) and Section 504 (subsection E) of the Rehabilitation Act. The intent of which is to provide access for otherwise qualified persons. SUNY Poly is not required to lower or substantially modify essential academic requirements, or make modifications that would fundamentally alter the nature of a service, program, or activity or that would result in an undue financial or administrative burden. Additionally, accommodation plans must be updated each semester.

The Disabilities Services Office is happy to advocate or coordinate with outside service providers, by student request and with written consent to communicate. Parents should be aware that legal rights and responsibilities change from high school to the college, both in terms of the type of support provided and in terms of parental involvement in the process. Students are solely responsible for self-identifying and following up with our office for any needs that they may have. Any student who wishes to have our office communicate with a parent must sign a written consent for permission to communicate.

### Course Syllabus Disclosure Statement Spring 2018

Accommodations for Students with Disabilities registered at SUNY Polytechnic Institute

> In compliance with the Americans with Disabilities Act of 1990 and with Section 504 of the Rehabilitation Act, SUNY Polytechnic Institute is committed to ensuring educational access and accommodations for all its registered students seeking access to meet course requirements and fully participate in programs or activities. SUNY Poly students with documented disabilities and medical conditions are encouraged to request these services by registering with the Disability Services Office and discussing your need for accommodations. For information or an appointment contact Director of Disability Services, located in Utica, B101 Kunsela Hall and in Albany in the Student Services Suite 309 Nano Fab South or by phone (315) 792-7170; or by email ds@sunyit.edu.


## Instructor's Notes

-  **Understanding vs Computation**: This course will focus on understanding financial concepts over merely calculating a number. Any calculation you will see as an undergrad has already been implemented in 20+ different programming languages.  You will never get a job as a calculator.  The value of the financial analyst is in undertanding what a calculation does, what the output means, etc.  You must be able to use the appropriate calculation in a given situation, and able to understand its output to make financial decisions.

-  **Spreadsheet Skills**:  The above does not mean you do not need to know how to calculate financial values.  You need to be able to do so in a spreadsheet, and increasingly with some programming language (python, javascript, R, etc). The point here is that the correct calculation is the minimal amount of work you can do.  It is the easiest part.  The harder, and more important aspect, is understanding what you are doing. 

-  Accordingly many *computation* questions on the exams can be solved through logic---knowing that 3 of 4 potential answers are not possible.
